global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'project_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['project-service:8080']
        labels:
          application: 'Project Service Application'
  - job_name: 'fetch_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fetch-service:8080']
        labels:
          application: 'Fetch Service Application'
  - job_name: 'inventory_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8080']
        labels:
          application: 'Inventory Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'